import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      boxShadow: {
        "glow-teal": "0 0 30px rgba(0, 229, 200, 0.35)",
      },
      colors: {
        "tier-1": "#0A0E0E",
        "tier-2": "#111718",
        "tier-3": "#161E1F",
        "surface-container": "#1d2023",
        "inverse-primary": "#494bd6",
        "surface-tint": "#c0c1ff",
        "tertiary-container": "#d97721",
        "on-primary-fixed": "#07006c",
        "on-surface-variant": "#c7c4d7",
        background: "#111718",
        "on-primary": "#1000a9",
        "on-tertiary-container": "#452000",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-surface": "#e1e2e7",
        "on-secondary-fixed": "#00201c",
        "on-tertiary": "#4f2500",
        "on-secondary-container": "#004d44",
        "on-secondary": "#003731",
        surface: "#111718",
        "surface-variant": "#323539",
        secondary: "#00E5C8",
        "secondary-fixed": "#62fae3",
        "surface-container-highest": "#323539",
        outline: "#908fa0",
        "outline-variant": "#464554",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#ffdcc5",
        "surface-container-low": "#191c1f",
        "inverse-on-surface": "#2e3134",
        "on-tertiary-fixed": "#301400",
        "surface-container-high": "#282a2e",
        primary: "#c0c1ff",
        "inverse-surface": "#e1e2e7",
        "surface-container-lowest": "#0A0E0E",
        "on-secondary-fixed-variant": "#005047",
        "primary-fixed-dim": "#c0c1ff",
        "on-tertiary-fixed-variant": "#703700",
        "secondary-fixed-dim": "#3cddc7",
        "on-error": "#690005",
        error: "#ffb4ab",
        tertiary: "#ffb783",
        "primary-container": "#8083ff",
        "on-background": "#e1e2e7",
        "primary-fixed": "#e1e0ff",
        "secondary-container": "#00C4AA",
        "surface-dim": "#111718",
        "tertiary-fixed-dim": "#ffb783",
        "surface-bright": "#37393d",
        "on-primary-container": "#0d0096",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Lexend", "sans-serif"],
        body: ["Lexend", "sans-serif"],
        label: ["Lexend", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
